# ===============================
# Server
# ===============================
server:
  port: 8081
  servlet.jsp.init-parameters.development: true
# ===============================
# Mail
# ===============================
mail:
  username: hoangmd265@gmail.com
  password: nobita123
# ===============================
# Application
# ===============================
application:
  alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz -_.
  iterations: 10000
  key_length: 256
  encrypt_type: PBKDF2WithHmacSHA1
# ===============================
# DATABASE
# ===============================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/webtool?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    continue-on-error: true
    platform: mysql
    tomcat:
      jmx-enabled: true
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
    static-path-pattern: /**